version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  animal-detector-resnet50-opt:
    lang: python3-http-debian
    handler: ./animal-detector-resnet50-opt
    image: keidikei/animal-detector-resnet50-opt:latest

